server:
  port: ${PORT:10000}

spring:
  data:
    mongodb:
#      uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_IP}:27017/UUUMusic?authSource=admin
#      uri: mongodb://localhost:27017/unreal-realms?authSource=admin
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_IP}/unreal-realms?authSource=admin
